language: node_js
node_js:
- 7.8.0
script: npm run build

before_deploy:
  echo $TRAVIS_BRANCH > release.txt
  
deploy:
  provider: releases
  api_key:
    secure: NczkkhNfChoumKdcnEdl8kGlHdD6mWRCegvv6ZtRFyi5a9uUL7bCd5fjcmuSBiCVm2vM4h0M/l9dLIF1bq8lY33O1WVVKuswR9Au60b3DDcS0MyIRxGRxbHb5WTTLOEjP+XDnzI5PUPXxTZ75mbmsHFTkDcZ4gruvbfRZg5BMoYRJ3l/7qBAjkLkNFI50Jvr0EetzCnCp4icMAiq0r7e8r1vTG9/rrDAQRjx39wC9W91ACG+2RZVG/wNmuNXb0ClwvuZCEc5Zn5nNaux4BRQO1oVBH+MEACwVUqJQOKMrmJN2mdXzBzTMYDytI+eGQ4SHacB0FAt4XbyEqClswvwnQgq+k2FJkJPT0GxJRFXmZlSDRzwt5ctntWmU45ITORW6WgNt4zfsYeY4ti2F/+y4amH84o98jusk/exB9rpWX+OrgcYh8HunR3JTsNDnkF/LpRQcqRc3qgH9MHd8v+huIh3kNXoPtjXxroKHkmuwwbIALdD9ssc9YKL10/++zIpjBSQWmewGDk2cKDoQ2Xl8GvSyBwK5WjruxeuwgBACUfEVvBOqcHPjt741EVbp7gnl9KmpN3EcqHqvCFRn6PVRzrSF7UFZj0VhEcx3cRRMlM7OOsn0j3wmcZnr9RMIoH6U+EjfD3jkS2Je/U4Brqomo8CtcKz5ZCmdQJhNv5nQ6U=
  file: release.txt
  on:
    tag: true
